---
traefik_version: "3.5.4"
traefik_email: "mustermax@example.org"
traefik_domain: "localhost:8080"
traefik_dashboard: true
traefik_dashboard_domain: "localhost:8081"
traefik_services:
  - name: "site1"
    url: "http://ansible-demo-server-2:80"
  - name: "site2"
    url: "http://ansible-demo-server-3:80"