$ANSIBLE_VAULT;1.1;AES256
37636163396462316562386232663033636232326638353634353535386539306466376264663939
3030643337343666316337313630373331383733373263660a386566303439653466613261653761
37366633313537663063303634656535383663656265646335643237346465306533373137383263
3963633264303331300a316339373937363564363066326334356638393663646134396536366531
32643530303633623736393230363666633531376661313631633731383133333731393461376461
6336313931303036313363636632613865316332363662323961
