$ANSIBLE_VAULT;1.1;AES256
38633162616432633330623565383134343237393337326264376334623931303764653934393433
3534626263363832303339326662393237323463363934330a306234303734353333346532393361
36356334383132303966363861663739643062663932336435626665346366613939643237613066
3038333533386534660a313032643438366461656361313765366364326365633139316562643962
62336432633435386333323731343361353532353434653030626435353530653333333065336563
6539656339643761663837363931653163643664373662336337
